# Generated by Django 5.1.4 on 2025-01-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Введите id телеграм чата",
                max_length=50,
                null=True,
                verbose_name="Telegram chat id",
            ),
        ),
    ]
