# Generated by Django 5.1.4 on 2025-01-15 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Введите привычку",
                        max_length=100,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Введите место", max_length=100, verbose_name="Место"
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        help_text="Введите дату и время для начала привычки в формате YYYY-MM-DD HH:mm",
                        verbose_name="Время",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        default=120,
                        help_text="Укажите продолжительность выполнения в секундах",
                        verbose_name="Продолжительность выполнения в секундах",
                    ),
                ),
                (
                    "reward",
                    models.TextField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Укажите, если привычка публичная",
                        null=True,
                        verbose_name="Публичность",
                    ),
                ),
                (
                    "pleasant_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка, которую можно привязать к полезной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("Каждый день", "Every day"),
                            ("Через день", "Every second day"),
                            ("Раз в три дня", "Every third day"),
                            ("Раз в неделю", "Once a week"),
                        ],
                        default="Каждый день",
                        help_text="Выберите периодичность",
                        max_length=25,
                        verbose_name="Переодичность",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите создателя привычки",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "related_pleasant_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите приятную привычку, связанную с текущей полезной",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="Связанная приятная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
