# Generated by Django 5.1.4 on 2025-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveSmallIntegerField(
                default=120,
                help_text="Укажите продолжительность выполнения в секундах",
                verbose_name="Продолжительность выполнения в секундах",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.TextField(
                blank=True,
                help_text="Укажите вознаграждение",
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
