# Generated by Django 5.1.4 on 2025-01-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                help_text="Введите дату и время для начала привычки в формате YYYY-MM-DD HH:mm",
                verbose_name="Время",
            ),
        ),
    ]
