# Generated by Django 5.1.4 on 2025-01-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                help_text="Введите дату и время для начала привычки в формате YYYY-MM-DD HH:mm",
                verbose_name="Время",
            ),
        ),
    ]
